/**: # namespace and node name
  ros__parameters:
    qos_depth: 30
    num_target: 3
    pick_target: 1
    max_speed : 1.0  # [m/s]
    min_speed : -0.5  # [m/s]
    max_yaw_rate : 0.69777 # 40.0 * math.pi / 180.0  # [rad/s]
    max_accel : 0.2  # [m/ss]
    max_delta_yaw_rate : 0.69777 # 40.0 * math.pi / 180.0 # [rad/ss]
    v_resolution : 0.01  # [m/s]
    yaw_rate_resolution : 0.0017444 # 0.1 * math.pi / 180.0  # [rad/s]
    dt : 0.1  # [s] Time tick for motion prediction
    predict_time : 3.0  # [s]
    to_goal_cost_gain : 0.15
    speed_cost_gain : 1.0
    obstacle_cost_gain : 1.0
    robot_stuck_flag_cons : 0.001  # constant to prevent robot stucked
    robot_type : 0 # 0 for circle, 1 for rectangle